/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.forms;

import ui.components.tab.CustomTab;
import ui.tabs.Tab_StatisticsCustomers;
import ui.tabs.Tab_StatisticsRevenue;

/**
 *
 * @author Lenovo
 */
public class Form_Statistics extends javax.swing.JPanel {

    /**
     * Creates new form Form_Statistics
     */
    public Form_Statistics() {
        initTabs();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(customTab, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(customTab, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initTabs(){
        customTab = new CustomTab();

        Tab_StatisticsRevenue tabRevenue = new Tab_StatisticsRevenue();
        Tab_StatisticsCustomers tabCustomer = new Tab_StatisticsCustomers();

        customTab.addTabPanel("Thống kê doanh thu", tabRevenue);
        customTab.addTabPanel("Thống kê khách hàng", tabCustomer);;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private CustomTab customTab;
}
