/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.forms;

/**
 *
 * @author TRAN LONG VU
 */
public class Form_Booking extends javax.swing.JPanel {

    /**
     * Creates new form Form_Booking
     */
    public Form_Booking() {
        initTabs();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customTab, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customTab, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initTabs(){
        customTab = new ui.components.tab.CustomTab();

        tabBooking = new ui.tabs.Tab_Booking();
        tabListBooking = new ui.tabs.Tab_ListBooking();
        tabBookingByTime = new ui.tabs.Tab_BookingByTime();
        tabListOrder = new ui.tabs.Tab_ListOrder();

        customTab.addTabPanel("Đặt phòng theo đêm", tabBooking);
        customTab.addTabPanel("Đặt phòng theo giờ", tabBookingByTime);
        customTab.addTabPanel("Danh sách đặt phòng", tabListBooking);
        customTab.addTabPanel("Danh sách hóa đơn", tabListOrder);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.components.tab.CustomTab customTab;
    private ui.tabs.Tab_Booking tabBooking;
    private ui.tabs.Tab_ListBooking tabListBooking;
    private ui.tabs.Tab_BookingByTime tabBookingByTime;
    private ui.tabs.Tab_ListOrder tabListOrder;

    // End of variables declaration//GEN-END:variables
}
